# Generated by Django 3.0.4 on 2020-03-11 19:29

from django.db import migrations, models


def add_data(apps, schema_editor):
    model = apps.get_model('account', 'Account')
    model.objects.create(uuid='26c940a1-7228-4ea2-a3bce6460b17204', name='Петров Иван Сергеевич',
                         balance=1700, hold=300, status=True)
    model.objects.create(uuid='7badc8f8-65bc-449a-8cde855234ac63e1', name='Kazitsky Jason',
                         balance=200, hold=200, status=True)
    model.objects.create(uuid='5597cc3d-c948-48a0-b711393edf20d9c0', name='Пархоменко Антон Александрович',
                         balance=10, hold=300, status=True)
    model.objects.create(uuid='867f0924-a917-4711-939b90b179a96392', name='Петечкин Петр Измаилович',
                         balance=1000000, hold=1, status=False)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('uuid', models.CharField(max_length=34, primary_key=True, serialize=False, verbose_name='uuid')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('balance', models.IntegerField(verbose_name='Баланс')),
                ('hold', models.IntegerField(verbose_name='Холд')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
            ],
        ),
        migrations.RunPython(add_data),
    ]
